/**
 * Supabase Database Types
 *
 * This file will be auto-generated by Supabase CLI:
 * npx supabase gen types typescript --project-id your-project-id > database.types.ts
 *
 * For now, providing base structure for DK-HQ audit platform
 */

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export interface Database {
  public: {
    Tables: {
      // Users & Organizations
      organizations: {
        Row: {
          id: string;
          name: string;
          slug: string;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          name: string;
          slug: string;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          id?: string;
          name?: string;
          slug?: string;
          updated_at?: string;
        };
      };

      profiles: {
        Row: {
          id: string;
          user_id: string;
          organization_id: string;
          role: 'admin' | 'manager' | 'staff';
          first_name: string | null;
          last_name: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          user_id: string;
          organization_id: string;
          role?: 'admin' | 'manager' | 'staff';
          first_name?: string | null;
          last_name?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          role?: 'admin' | 'manager' | 'staff';
          first_name?: string | null;
          last_name?: string | null;
          updated_at?: string;
        };
      };

      // Clients
      clients: {
        Row: {
          id: string;
          organization_id: string;
          company_number: string | null;
          name: string;
          industry: string | null;
          year_end_date: string | null;
          xero_tenant_id: string | null;
          quickbooks_realm_id: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          organization_id: string;
          company_number?: string | null;
          name: string;
          industry?: string | null;
          year_end_date?: string | null;
          xero_tenant_id?: string | null;
          quickbooks_realm_id?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          company_number?: string | null;
          name?: string;
          industry?: string | null;
          year_end_date?: string | null;
          xero_tenant_id?: string | null;
          quickbooks_realm_id?: string | null;
          updated_at?: string;
        };
      };

      // Audit Engagements
      engagements: {
        Row: {
          id: string;
          client_id: string;
          organization_id: string;
          year_end: string;
          status: 'planning' | 'fieldwork' | 'review' | 'completion' | 'signed_off';
          lead_partner_id: string | null;
          manager_id: string | null;
          materiality_overall: number | null;
          materiality_performance: number | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          client_id: string;
          organization_id: string;
          year_end: string;
          status?: 'planning' | 'fieldwork' | 'review' | 'completion' | 'signed_off';
          lead_partner_id?: string | null;
          manager_id?: string | null;
          materiality_overall?: number | null;
          materiality_performance?: number | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          status?: 'planning' | 'fieldwork' | 'review' | 'completion' | 'signed_off';
          lead_partner_id?: string | null;
          manager_id?: string | null;
          materiality_overall?: number | null;
          materiality_performance?: number | null;
          updated_at?: string;
        };
      };

      // Working Papers
      working_papers: {
        Row: {
          id: string;
          engagement_id: string;
          section: string;
          reference: string;
          title: string;
          content: Json;
          prepared_by: string | null;
          reviewed_by: string | null;
          status: 'draft' | 'prepared' | 'reviewed' | 'approved';
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          engagement_id: string;
          section: string;
          reference: string;
          title: string;
          content?: Json;
          prepared_by?: string | null;
          reviewed_by?: string | null;
          status?: 'draft' | 'prepared' | 'reviewed' | 'approved';
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          section?: string;
          reference?: string;
          title?: string;
          content?: Json;
          reviewed_by?: string | null;
          status?: 'draft' | 'prepared' | 'reviewed' | 'approved';
          updated_at?: string;
        };
      };

      // Risk Assessment
      risk_assessments: {
        Row: {
          id: string;
          engagement_id: string;
          area: string;
          inherent_risk: 'low' | 'medium' | 'high';
          control_risk: 'low' | 'medium' | 'high';
          detection_risk: 'low' | 'medium' | 'high';
          combined_risk: 'low' | 'medium' | 'high';
          notes: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          engagement_id: string;
          area: string;
          inherent_risk?: 'low' | 'medium' | 'high';
          control_risk?: 'low' | 'medium' | 'high';
          detection_risk?: 'low' | 'medium' | 'high';
          combined_risk?: 'low' | 'medium' | 'high';
          notes?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          inherent_risk?: 'low' | 'medium' | 'high';
          control_risk?: 'low' | 'medium' | 'high';
          detection_risk?: 'low' | 'medium' | 'high';
          combined_risk?: 'low' | 'medium' | 'high';
          notes?: string | null;
          updated_at?: string;
        };
      };

      // Audit Procedures
      audit_procedures: {
        Row: {
          id: string;
          engagement_id: string;
          working_paper_id: string | null;
          procedure_type: 'test_of_control' | 'substantive_analytical' | 'substantive_detail';
          area: string;
          description: string;
          result: string | null;
          conclusion: string | null;
          performed_by: string | null;
          performed_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: {
          id?: string;
          engagement_id: string;
          working_paper_id?: string | null;
          procedure_type: 'test_of_control' | 'substantive_analytical' | 'substantive_detail';
          area: string;
          description: string;
          result?: string | null;
          conclusion?: string | null;
          performed_by?: string | null;
          performed_at?: string | null;
          created_at?: string;
          updated_at?: string;
        };
        Update: {
          result?: string | null;
          conclusion?: string | null;
          performed_by?: string | null;
          performed_at?: string | null;
          updated_at?: string;
        };
      };
    };

    Views: {};

    Functions: {};

    Enums: {
      user_role: 'admin' | 'manager' | 'staff';
      engagement_status: 'planning' | 'fieldwork' | 'review' | 'completion' | 'signed_off';
      risk_level: 'low' | 'medium' | 'high';
      working_paper_status: 'draft' | 'prepared' | 'reviewed' | 'approved';
      procedure_type: 'test_of_control' | 'substantive_analytical' | 'substantive_detail';
    };
  };
}
